name: chatapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to pub.dev.
# Remove this line if you wish to publish to pub.dev.
publish_to: 'none'

# Version and build number for your application.
# Update versionName and versionCode for Android, and CFBundleShortVersionString and CFBundleVersion for iOS.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # Adding custom fonts
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
